#!/bin/env bash
# this directory
THIS="${HOME}"/clones/configs
# sync vimrc, and vim directory (plugins)
rsync "${HOME}"/.vimrc "${THIS}"/.vimrc
rsync -r "${HOME}"/.vim/ "${THIS}"/.vim/
# sync bash aliases
rsync "$HOME"/.bash_aliases "${THIS}"/.bash_aliases
#sync wallpapers/
rsync -r "$HOME"/wallpaper/ "${THIS}"/wallpaper/ # wallpaper/ == contents
#sync awesome/
rsync -r "$HOME"/.config/awesome/ "${THIS}"/.config/awesome/
#sync polybar/
rsync -r "$HOME"/.config/polybar/ "${THIS}"/.config/polybar/
# sync alacritty terminal emulator config
rsync "$HOME"/.config/alacritty.yml "${THIS}"/.config/alacritty.yml
# sync all the installed software for resetting system
rsync "$HOME"/clones/documents/md/linux/installedSoftware.md "${THIS}"/installed.md
# sync netplan basic config. Uses networkd, which needs wpa_supplicant installed.
rsync -r /etc/netplan/ "${THIS}"/netplan/
# sync own local scripts
rsync "${HOME}"/.local/bin/* "${THIS}"/bin/ --exclude "node_modules"
